# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 2.3.0"

ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|
  config.vm.box = "fedora/36-cloud-base"
  config.vm.box_version = "36-20220504.1"
  config.vm.box_check_update = true
  config.vm.box_url = "https://app.vagrantup.com/fedora/boxes/36-cloud-base"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true   
	vb.check_guest_additions = true
    vb.memory = "4096"
    vb.cpus = 4
  end
  config.vm.allow_fstab_modification = true
  config.vm.allow_hosts_modification = true
  config.vm.hostname = "Fedora28Workstation"
  config.vm.base_address = "192.168.6.22"
  config.vm.communicator = "ssh"
  config.ssh.insert_key = true
  config.vm.graceful_halt_timeout = 60
  config.vm.boot_timeout = 300
  config.vm.post_up_message = "This Environment was Created by Erick Quinteros"
  config.vm.provision "shell", path: "Scripts/basic.sh", name: "vagrant", privileged: true
  config.vm.provision "shell", path: "Scripts/shell.sh", name: "vagrant", privileged: true
  config.vm.provision "shell", path: "Scripts/user.sh", name: "vagrant", privileged: true
  config.vm.provision "shell", path: "Scripts/development.sh", name: "vagrant", privileged: true
  config.vm.provision "shell", path: "Scripts/gui.sh", name: "vagrant", privileged: true
end
